name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        conda env create -f environment_env1.yaml
        conda env create -f environment_tf.yaml
        pip install streamlit
        
    - name: Run Streamlit app
      run: |
        streamlit run streamlit.py
